name: Python Safety
# https://github.com/pyupio/safety

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    - cron: '0 0 * * 2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: Check dependencies with Safety
        run: |
          python -m pip -q install --upgrade pip
          pip -q install safety
          safety check -r requirements.txt

